# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""Shared read/normalize/write surface for ``~/.onex/config.yaml`` (OMN-16037).

Every command that touches the user config goes through this module so the file
has exactly one schema. ``onex config init`` (``cli_config.py``), ``onex init
--user-config`` (``cli_init.py``) and ``onex refresh-credentials``
(``cli_refresh_credentials.py``) previously each had their own private
``_config_path`` helper and their own idea of the file's shape.

Two invariants this module exists to hold:

* **One schema.** Managed sections are validated through
  :class:`~omnibase_core.models.cli.model_cli_user_config.ModelCliUserConfig`,
  so both writers emit identical structure.
* **No silent data loss.** Validated managed sections are *merged back over* the
  raw mapping rather than replacing it. Sections ONEX does not manage (the
  ``aws:`` block written by ``onex refresh-credentials``) and hand-added keys
  inside managed sections (an extra credential) survive every rewrite.
"""

from __future__ import annotations

from collections.abc import Mapping
from pathlib import Path

import yaml
from pydantic import BaseModel

from omnibase_core.enums.enum_core_error_code import EnumCoreErrorCode
from omnibase_core.enums.enum_user_config_mode import (
    LEGACY_MODE_ALIASES,
    EnumUserConfigMode,
)
from omnibase_core.errors.model_onex_error import ModelOnexError
from omnibase_core.models.cli.model_cli_user_config import (
    MANAGED_SECTIONS,
    USER_CONFIG_VERSION,
    ModelCliUserConfig,
)
from omnibase_core.types.type_serializable_value import (
    SerializableValue,
    SerializedDict,
)

# Commented starter file written on a *fresh* install. YAML round-tripping drops
# comments, so migrations render via ``yaml.dump`` instead; this literal is the
# only place onboarding hints live. ``test_template_matches_model_defaults``
# asserts it parses to exactly ``default_user_config()``, which is what stops
# this template and the model from drifting apart again.
USER_CONFIG_TEMPLATE = """\
# ~/.onex/config.yaml — ONEX user configuration
# Generated by: onex config init  (equivalently: onex init --user-config)

version: 1

# local = Mode A (no cloud dependency); cloud = Mode B (cloud-connected)
mode: local

credentials:
  # required: get from https://linear.app/settings/api
  LINEAR_API_KEY: ""
  # optional: only needed for Mode B (cloud-connected)
  INFISICAL_TOKEN: ""

paths:
  state_dir: ~/.onex/state
  log_dir: ~/.onex/logs
  worktrees_root: ~/omni_worktrees

kafka:
  bootstrap_servers: localhost:19092

logging:
  level: INFO
"""

_SECTION_MODELS: dict[str, type[BaseModel]] = {
    name: field.annotation
    for name, field in ModelCliUserConfig.model_fields.items()
    if isinstance(field.annotation, type) and issubclass(field.annotation, BaseModel)
}


def user_config_path(onex_home: Path | None = None) -> Path:
    """Resolve the config file location, honouring a test/override home."""
    home = onex_home if onex_home is not None else Path.home() / ".onex"
    return home / "config.yaml"


def default_user_config() -> SerializedDict:
    """The managed schema with every default applied, as plain YAML types."""
    return ModelCliUserConfig().model_dump(by_alias=True, mode="json")


def _known_keys(model: type[BaseModel]) -> set[str]:
    keys: set[str] = set()
    for name, field in model.model_fields.items():
        keys.add(name)
        if field.alias is not None:
            keys.add(field.alias)
    return keys


def _resolve_version(raw: Mapping[str, SerializableValue]) -> int:
    raw_version = raw.get("version", USER_CONFIG_VERSION)
    if isinstance(raw_version, bool) or not isinstance(raw_version, int):
        raise ModelOnexError(
            f"'version' must be an integer, got {raw_version!r}. "
            "Fix the value in ~/.onex/config.yaml.",
            EnumCoreErrorCode.INVALID_CONFIGURATION,
        )
    if raw_version > USER_CONFIG_VERSION:
        raise ModelOnexError(
            f"'version' is {raw_version}, newer than this ONEX build understands "
            f"({USER_CONFIG_VERSION}). Upgrade omnibase-core rather than "
            "downgrading the file.",
            EnumCoreErrorCode.INVALID_CONFIGURATION,
        )
    # Older or absent versions are migrated up; the writer always stamps current.
    return USER_CONFIG_VERSION


def _resolve_mode(raw: Mapping[str, SerializableValue]) -> str:
    raw_mode: SerializableValue = raw.get("mode", EnumUserConfigMode.LOCAL.value)
    if isinstance(raw_mode, EnumUserConfigMode):
        raw_mode = raw_mode.value
    if not isinstance(raw_mode, str):
        raise ModelOnexError(
            f"'mode' must be a string, got {raw_mode!r}. Expected one of: local, cloud.",
            EnumCoreErrorCode.INVALID_CONFIGURATION,
        )
    resolved = LEGACY_MODE_ALIASES.get(raw_mode, raw_mode)
    valid = {member.value for member in EnumUserConfigMode}
    if resolved not in valid:
        raise ModelOnexError(
            f"unsupported 'mode' value {raw_mode!r}. "
            f"Expected one of: {', '.join(sorted(valid))}.",
            EnumCoreErrorCode.INVALID_CONFIGURATION,
        )
    return resolved


def _deep_merge(
    base: Mapping[str, SerializableValue], override: Mapping[str, SerializableValue]
) -> SerializedDict:
    """Merge ``override`` onto ``base``; keys only in ``base`` are preserved."""
    merged: SerializedDict = dict(base)
    for key, value in override.items():
        current = merged.get(key)
        if isinstance(current, Mapping) and isinstance(value, Mapping):
            merged[key] = _deep_merge(current, value)
        else:
            merged[key] = value
    return merged


def normalize_user_config(
    raw: Mapping[str, SerializableValue] | None,
) -> tuple[SerializedDict, bool]:
    """Normalize any legacy or current config onto the surviving schema.

    Accepts either historical shape — the ``{mode: standalone, kafka, logging}``
    file written by pre-OMN-16037 ``onex config init``, or the
    ``{version, mode, credentials, paths}`` file written by ``onex init
    --user-config`` — plus anything already normalized.

    Returns ``(normalized, migrated)`` where ``migrated`` is True when the result
    differs from the input, i.e. the caller should write the file back.

    Raises:
        ModelOnexError: the file is structurally unusable (a managed section that is
            not a mapping, an unknown ``mode``, a future schema ``version``).
            Callers at the CLI boundary surface this as a user-facing error
            rather than silently rewriting a file they did not understand.
    """
    if raw is None:
        raw = {}
    if not isinstance(raw, Mapping):
        raise ModelOnexError(
            f"~/.onex/config.yaml must contain a mapping at the top level, "
            f"got {type(raw).__name__}.",
            EnumCoreErrorCode.INVALID_CONFIGURATION,
        )

    payload: SerializedDict = {
        "version": _resolve_version(raw),
        "mode": _resolve_mode(raw),
    }

    for name, section_model in _SECTION_MODELS.items():
        if name not in raw:
            continue
        section = raw[name]
        if section is None:
            # A section header with no children (``logging:``) parses to None.
            # It carries no values, so fill that section's defaults instead of
            # refusing the whole file.
            payload[name] = {}
            continue
        if not isinstance(section, Mapping):
            raise ModelOnexError(
                f"'{name}' must be a mapping in ~/.onex/config.yaml, "
                f"got {type(section).__name__}.",
                EnumCoreErrorCode.INVALID_CONFIGURATION,
            )
        known = _known_keys(section_model)
        # Unknown keys are filtered out before validation (the section models are
        # extra="forbid") and merged back in below, so they are preserved without
        # loosening the schema.
        payload[name] = {k: v for k, v in section.items() if k in known}

    managed = ModelCliUserConfig.model_validate(payload).model_dump(
        by_alias=True, mode="json"
    )

    normalized: SerializedDict = {}
    for name in MANAGED_SECTIONS:
        managed_value = managed[name]
        raw_value = raw.get(name)
        if isinstance(raw_value, Mapping) and isinstance(managed_value, Mapping):
            normalized[name] = _deep_merge(raw_value, managed_value)
        else:
            normalized[name] = managed_value
    for key, value in raw.items():
        if key not in MANAGED_SECTIONS:
            normalized[key] = value

    return normalized, normalized != dict(raw)


def render_user_config(config: Mapping[str, SerializableValue]) -> str:
    """Serialize a normalized config, preserving managed-section key order."""
    return str(yaml.dump(dict(config), default_flow_style=False, sort_keys=False))


def parse_user_config_text(text: str, source: str) -> SerializedDict | None:
    """Parse raw ``~/.onex/config.yaml`` text into a mapping.

    The single raw-YAML entry point for this file. It sits *before* Pydantic:
    the config legitimately carries sections ONEX does not model (the ``aws:``
    block, hand-added keys), so no single model can validate the document. The
    managed subset is validated by ``ModelCliUserConfig`` in
    :func:`normalize_user_config` immediately after.

    Returns ``None`` for an empty document.

    Raises:
        ModelOnexError: the text is not valid YAML, or does not parse to a
            mapping.
    """
    try:
        parsed = yaml.safe_load(text)
    except yaml.YAMLError as exc:
        raise ModelOnexError(
            f"{source} is not valid YAML: {exc}",
            EnumCoreErrorCode.INVALID_CONFIGURATION,
        ) from exc

    if parsed is None:
        return None
    if not isinstance(parsed, dict):
        raise ModelOnexError(
            f"{source} must contain a mapping at the top level, "
            f"got {type(parsed).__name__}.",
            EnumCoreErrorCode.INVALID_CONFIGURATION,
        )
    return parsed


def read_user_config(path: Path) -> SerializedDict | None:
    """Parse the config file. Returns ``None`` for an empty file.

    Raises:
        ModelOnexError: the file is not valid YAML, or is not a mapping.
    """
    return parse_user_config_text(path.read_text(), str(path))


def write_user_config(path: Path, config: Mapping[str, SerializableValue]) -> None:
    """Write a normalized config, creating the parent directory if needed."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(render_user_config(config))


def bootstrap_user_config(path: Path) -> None:
    """Write the commented starter file for a fresh install."""
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(USER_CONFIG_TEMPLATE)


def migrate_user_config_file(path: Path) -> bool:
    """Rewrite an existing file onto the current schema, preserving its values.

    Returns True when the file's content changed.
    """
    normalized, migrated = normalize_user_config(read_user_config(path))
    write_user_config(path, normalized)
    return migrated


__all__ = [
    "MANAGED_SECTIONS",
    "USER_CONFIG_TEMPLATE",
    "USER_CONFIG_VERSION",
    "bootstrap_user_config",
    "default_user_config",
    "migrate_user_config_file",
    "normalize_user_config",
    "parse_user_config_text",
    "read_user_config",
    "render_user_config",
    "user_config_path",
    "write_user_config",
]
