# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""``onex config`` — read and initialize ~/.onex/config.yaml."""

from __future__ import annotations

import sys
from pathlib import Path

import click
import yaml

_DEFAULT_CONFIG = """\
# ONEX standalone configuration (Mode A — no AWS)
# Generated by: onex config init

mode: standalone

kafka:
  bootstrap_servers: localhost:19092

logging:
  level: INFO

# Uncomment to enable AWS credential refresh:
# aws:
#   secret_name: your-secret-name
#   region: us-east-1
"""


def _config_path() -> Path:
    return Path.home() / ".onex" / "config.yaml"


@click.group("config")
def config_group() -> None:  # stub-ok
    """Manage ONEX configuration."""


@config_group.command("init")
@click.option(
    "--force",
    is_flag=True,
    default=False,
    help="Overwrite existing config file.",
)
def config_init(force: bool) -> None:
    """Scaffold ~/.onex/config.yaml with default placeholders.

    Creates a starter configuration file for standalone ONEX operation
    (Mode A, no AWS). Use --force to overwrite an existing file.
    """
    config_file = _config_path()

    if config_file.exists() and not force:
        click.echo(
            f"Error: {config_file} already exists. Use --force to overwrite.",
            err=True,
        )
        sys.exit(1)

    config_file.parent.mkdir(parents=True, exist_ok=True)
    config_file.write_text(_DEFAULT_CONFIG)

    click.echo(f"Configuration initialized at {config_file}")


@config_group.command("get")
@click.argument("key")
def config_get(key: str) -> None:
    """Read a value from ~/.onex/config.yaml.

    Supports dotted keys for nested access (e.g. kafka.bootstrap_servers).
    """
    config_file = _config_path()

    if not config_file.exists():
        click.echo(
            f"Error: config file not found at {config_file}. "
            "Run 'onex config init' first.",
            err=True,
        )
        sys.exit(1)

    with open(config_file) as f:
        data = yaml.safe_load(f)

    if data is None:
        click.echo("Error: config file is empty", err=True)
        sys.exit(1)

    parts = key.split(".")
    value = data
    for part in parts:
        if not isinstance(value, dict) or part not in value:
            click.echo(f"Error: key '{key}' not found in config", err=True)
            sys.exit(1)
        value = value[part]

    if isinstance(value, dict):
        click.echo(yaml.dump(value, default_flow_style=False).rstrip())
    else:
        click.echo(str(value))
