# Pre-commit hooks exported by omnibase_core.
# Consumers reference these via:
#
#   - repo: https://github.com/OmniNode-ai/omnibase_core
#     rev: <tag>
#     hooks:
#       - id: check-local-paths

- id: check-local-paths
  name: Check for local path references
  description: >
    Detect machine-specific absolute paths (/Volumes/..., /Users/..., /home/...,
    C:\Users\...) that break portability when code or skills are distributed.
    Add `# local-path-ok` to suppress a specific line.
  language: python
  entry: python -m omnibase_core.validation.validator_local_paths
  types: [text]
  pass_filenames: true
  stages: [pre-commit]
