# Stub Implementation Checker Configuration
# Copy to .stub-check-config.yaml and customize as needed

# Files to exclude from stub checking (exact filenames)
excluded_files:
  - __init__.py
  - conftest.py

# Path patterns to exclude from stub checking
excluded_patterns:
  - /tests/fixtures/
  - /examples/experimental/
  - /prototypes/
  - /archived/

# Function names to exclude from stub checking
excluded_functions:
  - setup
  - teardown
  - fixture
  - mock_factory
