# YAML Validation Allowlist Configuration
#
# This file configures which files are allowed to use yaml.safe_load() and
# direct YAML field access in the validate-no-manual-yaml.py pre-commit hook.
#
# Add files/patterns here when they legitimately need raw YAML parsing for:
# - Validation utilities that check YAML structure
# - Discovery APIs that load flexible metadata
# - Testing utilities that verify YAML serialization

# Specific file paths (relative to project root)
allowed_files:
  - "src/omnibase_core/validation/contracts.py"
  - "src/omnibase_core/validation/contract_validator.py"
  - "src/omnibase_core/discovery/mixin_discovery.py"
  - "src/omnibase_core/utils/safe_yaml_loader.py"
  - "src/omnibase_core/utils/utility_filesystem_reader.py"
  - "src/omnibase_core/utils/real_file_io.py"
  - "src/omnibase_core/utils/yaml_dict_loader.py"
  - "scripts/validation/validate-string-versions.py"
  - "scripts/validation/validate-no-manual-yaml.py"

# Filename patterns (checked against basename)
allowed_filenames:
  - "safe_yaml_loader.py"
  - "utility_filesystem_reader.py"
  - "real_file_io.py"
  - "yaml_dict_loader.py"
  - "validate-string-versions.py"

# Function names that are allowed to use yaml.safe_load()
allowed_functions:
  - "load_and_validate_yaml_model"
  - "load_yaml_content_as_model"
  - "_dump_yaml_content"
  - "extract_example_from_schema"
  - "read_yaml"
  - "load_yaml"
  - "_load_yaml_file"
  - "_load_config"
  - "load_yaml_as_dict"
  - "load_yaml_as_dict_with_validation"
  - "test_yaml_serialization_compatibility"
  - "test_yaml_deserialization_comprehensive"
  - "test_yaml_round_trip_serialization"
