"""
Comprehensive error codes for ONEX system.

Standardized error codes following ONEX conventions for consistent
error handling throughout the system. All error codes follow the
pattern: ONEX_<COMPONENT>_<NUMBER>_<DESCRIPTION>
"""

from enum import Enum


class EnumErrorCode(str, Enum):
    """
    Comprehensive error codes for ONEX system.

    All error codes follow the pattern: ONEX_<COMPONENT>_<NUMBER>_<DESCRIPTION>
    """

    # === CORE SYSTEM ERRORS (001-099) ===
    ONEX_CORE_001_INITIALIZATION_FAILED = "ONEX_CORE_001_INITIALIZATION_FAILED"
    ONEX_CORE_002_CONFIGURATION_INVALID = "ONEX_CORE_002_CONFIGURATION_INVALID"
    ONEX_CORE_003_DEPENDENCY_MISSING = "ONEX_CORE_003_DEPENDENCY_MISSING"
    ONEX_CORE_004_SERVICE_UNAVAILABLE = "ONEX_CORE_004_SERVICE_UNAVAILABLE"
    ONEX_CORE_005_CONTAINER_ERROR = "ONEX_CORE_005_CONTAINER_ERROR"
    ONEX_CORE_006_BOOTSTRAP_FAILED = "ONEX_CORE_006_BOOTSTRAP_FAILED"
    ONEX_CORE_007_HEALTH_CHECK_FAILED = "ONEX_CORE_007_HEALTH_CHECK_FAILED"
    ONEX_CORE_008_RESOURCE_EXHAUSTED = "ONEX_CORE_008_RESOURCE_EXHAUSTED"
    ONEX_CORE_009_SHUTDOWN_ERROR = "ONEX_CORE_009_SHUTDOWN_ERROR"
    ONEX_CORE_010_CRITICAL_FAILURE = "ONEX_CORE_010_CRITICAL_FAILURE"

    # === FILE SYSTEM ERRORS (011-030) ===
    ONEX_CORE_011_FILE_NOT_FOUND = "ONEX_CORE_011_FILE_NOT_FOUND"
    ONEX_CORE_012_FILE_ACCESS_DENIED = "ONEX_CORE_012_FILE_ACCESS_DENIED"
    ONEX_CORE_013_FILE_WRITE_FAILED = "ONEX_CORE_013_FILE_WRITE_FAILED"
    ONEX_CORE_014_FILE_READ_FAILED = "ONEX_CORE_014_FILE_READ_FAILED"
    ONEX_CORE_015_DIRECTORY_NOT_FOUND = "ONEX_CORE_015_DIRECTORY_NOT_FOUND"
    ONEX_CORE_016_DIRECTORY_CREATE_FAILED = "ONEX_CORE_016_DIRECTORY_CREATE_FAILED"
    ONEX_CORE_017_PATH_INVALID = "ONEX_CORE_017_PATH_INVALID"
    ONEX_CORE_018_PERMISSION_DENIED = "ONEX_CORE_018_PERMISSION_DENIED"
    ONEX_CORE_019_DISK_SPACE_FULL = "ONEX_CORE_019_DISK_SPACE_FULL"
    ONEX_CORE_020_FILE_LOCKED = "ONEX_CORE_020_FILE_LOCKED"
    ONEX_CORE_021_FILE_CORRUPTED = "ONEX_CORE_021_FILE_CORRUPTED"
    ONEX_CORE_022_SYMLINK_BROKEN = "ONEX_CORE_022_SYMLINK_BROKEN"

    # === VALIDATION ERRORS (031-050) ===
    ONEX_CORE_031_VALIDATION_FAILED = "ONEX_CORE_031_VALIDATION_FAILED"
    ONEX_CORE_032_SCHEMA_INVALID = "ONEX_CORE_032_SCHEMA_INVALID"
    ONEX_CORE_033_TYPE_MISMATCH = "ONEX_CORE_033_TYPE_MISMATCH"
    ONEX_CORE_034_VALUE_OUT_OF_RANGE = "ONEX_CORE_034_VALUE_OUT_OF_RANGE"
    ONEX_CORE_035_REQUIRED_FIELD_MISSING = "ONEX_CORE_035_REQUIRED_FIELD_MISSING"
    ONEX_CORE_036_FORMAT_INVALID = "ONEX_CORE_036_FORMAT_INVALID"
    ONEX_CORE_037_CONSTRAINT_VIOLATION = "ONEX_CORE_037_CONSTRAINT_VIOLATION"
    ONEX_CORE_038_ENUM_VALUE_INVALID = "ONEX_CORE_038_ENUM_VALUE_INVALID"
    ONEX_CORE_039_REGEX_PATTERN_FAILED = "ONEX_CORE_039_REGEX_PATTERN_FAILED"
    ONEX_CORE_040_LENGTH_CONSTRAINT_FAILED = "ONEX_CORE_040_LENGTH_CONSTRAINT_FAILED"

    # === PARSING ERRORS (051-070) ===
    ONEX_CORE_051_PARSING_FAILED = "ONEX_CORE_051_PARSING_FAILED"
    ONEX_CORE_052_JSON_INVALID = "ONEX_CORE_052_JSON_INVALID"
    ONEX_CORE_053_YAML_INVALID = "ONEX_CORE_053_YAML_INVALID"
    ONEX_CORE_054_XML_INVALID = "ONEX_CORE_054_XML_INVALID"
    ONEX_CORE_055_CSV_INVALID = "ONEX_CORE_055_CSV_INVALID"
    ONEX_CORE_056_TOML_INVALID = "ONEX_CORE_056_TOML_INVALID"
    ONEX_CORE_057_ENCODING_ERROR = "ONEX_CORE_057_ENCODING_ERROR"
    ONEX_CORE_058_SYNTAX_ERROR = "ONEX_CORE_058_SYNTAX_ERROR"
    ONEX_CORE_059_STRUCTURE_INVALID = "ONEX_CORE_059_STRUCTURE_INVALID"
    ONEX_CORE_060_CONTENT_MALFORMED = "ONEX_CORE_060_CONTENT_MALFORMED"

    # === NETWORK ERRORS (071-090) ===
    ONEX_CORE_071_NETWORK_ERROR = "ONEX_CORE_071_NETWORK_ERROR"
    ONEX_CORE_072_CONNECTION_FAILED = "ONEX_CORE_072_CONNECTION_FAILED"
    ONEX_CORE_073_TIMEOUT_ERROR = "ONEX_CORE_073_TIMEOUT_ERROR"
    ONEX_CORE_074_DNS_RESOLUTION_FAILED = "ONEX_CORE_074_DNS_RESOLUTION_FAILED"
    ONEX_CORE_075_SSL_ERROR = "ONEX_CORE_075_SSL_ERROR"
    ONEX_CORE_076_PROXY_ERROR = "ONEX_CORE_076_PROXY_ERROR"
    ONEX_CORE_077_RATE_LIMIT_EXCEEDED = "ONEX_CORE_077_RATE_LIMIT_EXCEEDED"
    ONEX_CORE_078_HTTP_ERROR = "ONEX_CORE_078_HTTP_ERROR"
    ONEX_CORE_079_WEBSOCKET_ERROR = "ONEX_CORE_079_WEBSOCKET_ERROR"
    ONEX_CORE_080_PROTOCOL_ERROR = "ONEX_CORE_080_PROTOCOL_ERROR"

    # === AUTHENTICATION/AUTHORIZATION ERRORS (091-110) ===
    ONEX_CORE_091_AUTH_FAILED = "ONEX_CORE_091_AUTH_FAILED"
    ONEX_CORE_092_UNAUTHORIZED = "ONEX_CORE_092_UNAUTHORIZED"
    ONEX_CORE_093_TOKEN_INVALID = "ONEX_CORE_093_TOKEN_INVALID"
    ONEX_CORE_094_TOKEN_EXPIRED = "ONEX_CORE_094_TOKEN_EXPIRED"
    ONEX_CORE_095_CREDENTIALS_INVALID = "ONEX_CORE_095_CREDENTIALS_INVALID"
    ONEX_CORE_096_ACCESS_DENIED = "ONEX_CORE_096_ACCESS_DENIED"
    ONEX_CORE_097_PERMISSION_INSUFFICIENT = "ONEX_CORE_097_PERMISSION_INSUFFICIENT"
    ONEX_CORE_098_SESSION_EXPIRED = "ONEX_CORE_098_SESSION_EXPIRED"
    ONEX_CORE_099_AUTH_PROVIDER_ERROR = "ONEX_CORE_099_AUTH_PROVIDER_ERROR"
    ONEX_CORE_100_SECURITY_VIOLATION = "ONEX_CORE_100_SECURITY_VIOLATION"

    # === DATABASE ERRORS (111-130) ===
    ONEX_DB_111_CONNECTION_FAILED = "ONEX_DB_111_CONNECTION_FAILED"
    ONEX_DB_112_QUERY_FAILED = "ONEX_DB_112_QUERY_FAILED"
    ONEX_DB_113_TRANSACTION_FAILED = "ONEX_DB_113_TRANSACTION_FAILED"
    ONEX_DB_114_CONSTRAINT_VIOLATION = "ONEX_DB_114_CONSTRAINT_VIOLATION"
    ONEX_DB_115_DEADLOCK_DETECTED = "ONEX_DB_115_DEADLOCK_DETECTED"
    ONEX_DB_116_DUPLICATE_KEY = "ONEX_DB_116_DUPLICATE_KEY"
    ONEX_DB_117_FOREIGN_KEY_VIOLATION = "ONEX_DB_117_FOREIGN_KEY_VIOLATION"
    ONEX_DB_118_TABLE_NOT_FOUND = "ONEX_DB_118_TABLE_NOT_FOUND"
    ONEX_DB_119_MIGRATION_FAILED = "ONEX_DB_119_MIGRATION_FAILED"
    ONEX_DB_120_BACKUP_FAILED = "ONEX_DB_120_BACKUP_FAILED"

    # === WORKFLOW ERRORS (131-150) ===
    ONEX_WORKFLOW_131_EXECUTION_FAILED = "ONEX_WORKFLOW_131_EXECUTION_FAILED"
    ONEX_WORKFLOW_132_TIMEOUT = "ONEX_WORKFLOW_132_TIMEOUT"
    ONEX_WORKFLOW_133_VALIDATION_FAILED = "ONEX_WORKFLOW_133_VALIDATION_FAILED"
    ONEX_WORKFLOW_134_STEP_FAILED = "ONEX_WORKFLOW_134_STEP_FAILED"
    ONEX_WORKFLOW_135_DEPENDENCY_FAILED = "ONEX_WORKFLOW_135_DEPENDENCY_FAILED"
    ONEX_WORKFLOW_136_STATE_INVALID = "ONEX_WORKFLOW_136_STATE_INVALID"
    ONEX_WORKFLOW_137_ROLLBACK_FAILED = "ONEX_WORKFLOW_137_ROLLBACK_FAILED"
    ONEX_WORKFLOW_138_RESOURCE_LOCKED = "ONEX_WORKFLOW_138_RESOURCE_LOCKED"
    ONEX_WORKFLOW_139_CONDITION_NOT_MET = "ONEX_WORKFLOW_139_CONDITION_NOT_MET"
    ONEX_WORKFLOW_140_CONFIGURATION_ERROR = "ONEX_WORKFLOW_140_CONFIGURATION_ERROR"

    # === PROCESSING ERRORS (151-170) ===
    ONEX_PROC_151_PROCESSING_FAILED = "ONEX_PROC_151_PROCESSING_FAILED"
    ONEX_PROC_152_TRANSFORMATION_FAILED = "ONEX_PROC_152_TRANSFORMATION_FAILED"
    ONEX_PROC_153_AGGREGATION_FAILED = "ONEX_PROC_153_AGGREGATION_FAILED"
    ONEX_PROC_154_FILTER_FAILED = "ONEX_PROC_154_FILTER_FAILED"
    ONEX_PROC_155_SORT_FAILED = "ONEX_PROC_155_SORT_FAILED"
    ONEX_PROC_156_MERGE_FAILED = "ONEX_PROC_156_MERGE_FAILED"
    ONEX_PROC_157_SPLIT_FAILED = "ONEX_PROC_157_SPLIT_FAILED"
    ONEX_PROC_158_COMPRESSION_FAILED = "ONEX_PROC_158_COMPRESSION_FAILED"
    ONEX_PROC_159_DECOMPRESSION_FAILED = "ONEX_PROC_159_DECOMPRESSION_FAILED"
    ONEX_PROC_160_SERIALIZATION_FAILED = "ONEX_PROC_160_SERIALIZATION_FAILED"

    # === API ERRORS (171-190) ===
    ONEX_API_171_ENDPOINT_NOT_FOUND = "ONEX_API_171_ENDPOINT_NOT_FOUND"
    ONEX_API_172_METHOD_NOT_ALLOWED = "ONEX_API_172_METHOD_NOT_ALLOWED"
    ONEX_API_173_REQUEST_INVALID = "ONEX_API_173_REQUEST_INVALID"
    ONEX_API_174_RESPONSE_INVALID = "ONEX_API_174_RESPONSE_INVALID"
    ONEX_API_175_CONTENT_TYPE_UNSUPPORTED = "ONEX_API_175_CONTENT_TYPE_UNSUPPORTED"
    ONEX_API_176_PAYLOAD_TOO_LARGE = "ONEX_API_176_PAYLOAD_TOO_LARGE"
    ONEX_API_177_VERSION_MISMATCH = "ONEX_API_177_VERSION_MISMATCH"
    ONEX_API_178_QUOTA_EXCEEDED = "ONEX_API_178_QUOTA_EXCEEDED"
    ONEX_API_179_THROTTLING_ACTIVE = "ONEX_API_179_THROTTLING_ACTIVE"
    ONEX_API_180_SERVICE_UNAVAILABLE = "ONEX_API_180_SERVICE_UNAVAILABLE"

    # === EXTERNAL SERVICE ERRORS (191-210) ===
    ONEX_EXT_191_SERVICE_ERROR = "ONEX_EXT_191_SERVICE_ERROR"
    ONEX_EXT_192_SERVICE_TIMEOUT = "ONEX_EXT_192_SERVICE_TIMEOUT"
    ONEX_EXT_193_SERVICE_UNAVAILABLE = "ONEX_EXT_193_SERVICE_UNAVAILABLE"
    ONEX_EXT_194_API_KEY_INVALID = "ONEX_EXT_194_API_KEY_INVALID"
    ONEX_EXT_195_QUOTA_EXCEEDED = "ONEX_EXT_195_QUOTA_EXCEEDED"
    ONEX_EXT_196_RATE_LIMITED = "ONEX_EXT_196_RATE_LIMITED"
    ONEX_EXT_197_RESPONSE_MALFORMED = "ONEX_EXT_197_RESPONSE_MALFORMED"
    ONEX_EXT_198_VERSION_INCOMPATIBLE = "ONEX_EXT_198_VERSION_INCOMPATIBLE"
    ONEX_EXT_199_CONTRACT_VIOLATION = "ONEX_EXT_199_CONTRACT_VIOLATION"
    ONEX_EXT_200_INTEGRATION_FAILED = "ONEX_EXT_200_INTEGRATION_FAILED"

    # === DOCUMENT FRESHNESS ERRORS (211-230) ===
    ONEX_FRESH_211_PATH_NOT_FOUND = "ONEX_FRESH_211_PATH_NOT_FOUND"
    ONEX_FRESH_212_ANALYSIS_FAILED = "ONEX_FRESH_212_ANALYSIS_FAILED"
    ONEX_FRESH_213_DATABASE_ERROR = "ONEX_FRESH_213_DATABASE_ERROR"
    ONEX_FRESH_214_AI_SERVICE_ERROR = "ONEX_FRESH_214_AI_SERVICE_ERROR"
    ONEX_FRESH_215_DEPENDENCY_ANALYSIS_FAILED = "ONEX_FRESH_215_DEPENDENCY_ANALYSIS_FAILED"
    ONEX_FRESH_216_CHANGE_DETECTION_FAILED = "ONEX_FRESH_216_CHANGE_DETECTION_FAILED"
    ONEX_FRESH_217_VALIDATION_FAILED = "ONEX_FRESH_217_VALIDATION_FAILED"
    ONEX_FRESH_218_CONFIG_INVALID = "ONEX_FRESH_218_CONFIG_INVALID"
    ONEX_FRESH_219_GIT_OPERATION_FAILED = "ONEX_FRESH_219_GIT_OPERATION_FAILED"
    ONEX_FRESH_220_RESOURCE_EXHAUSTED = "ONEX_FRESH_220_RESOURCE_EXHAUSTED"

    # === REDUCER PATTERN ERRORS (231-250) ===
    ONEX_REDUCER_231_WORKFLOW_ROUTING_FAILED = "ONEX_REDUCER_231_WORKFLOW_ROUTING_FAILED"
    ONEX_REDUCER_232_SUBREDUCER_NOT_FOUND = "ONEX_REDUCER_232_SUBREDUCER_NOT_FOUND"
    ONEX_REDUCER_233_WORKFLOW_EXECUTION_FAILED = "ONEX_REDUCER_233_WORKFLOW_EXECUTION_FAILED"
    ONEX_REDUCER_234_STATE_TRANSITION_FAILED = "ONEX_REDUCER_234_STATE_TRANSITION_FAILED"
    ONEX_REDUCER_235_INSTANCE_ISOLATION_FAILED = "ONEX_REDUCER_235_INSTANCE_ISOLATION_FAILED"
    ONEX_REDUCER_236_WORKFLOW_TIMEOUT = "ONEX_REDUCER_236_WORKFLOW_TIMEOUT"
    ONEX_REDUCER_237_WORKFLOW_CANCELLED = "ONEX_REDUCER_237_WORKFLOW_CANCELLED"
    ONEX_REDUCER_238_CONTEXT_INVALID = "ONEX_REDUCER_238_CONTEXT_INVALID"
    ONEX_REDUCER_239_DEPENDENCY_FAILED = "ONEX_REDUCER_239_DEPENDENCY_FAILED"
    ONEX_REDUCER_240_ROLLBACK_FAILED = "ONEX_REDUCER_240_ROLLBACK_FAILED"

    # === GENERIC ERRORS (251-270) ===
    ONEX_GENERIC_251_UNKNOWN_ERROR = "ONEX_GENERIC_251_UNKNOWN_ERROR"
    ONEX_GENERIC_252_NOT_IMPLEMENTED = "ONEX_GENERIC_252_NOT_IMPLEMENTED"
    ONEX_GENERIC_253_OPERATION_FAILED = "ONEX_GENERIC_253_OPERATION_FAILED"
    ONEX_GENERIC_254_INVALID_STATE = "ONEX_GENERIC_254_INVALID_STATE"
    ONEX_GENERIC_255_PRECONDITION_FAILED = "ONEX_GENERIC_255_PRECONDITION_FAILED"
    ONEX_GENERIC_256_POSTCONDITION_FAILED = "ONEX_GENERIC_256_POSTCONDITION_FAILED"
    ONEX_GENERIC_257_ASSERTION_FAILED = "ONEX_GENERIC_257_ASSERTION_FAILED"
    ONEX_GENERIC_258_INVARIANT_VIOLATION = "ONEX_GENERIC_258_INVARIANT_VIOLATION"
    ONEX_GENERIC_259_BUSINESS_RULE_VIOLATION = "ONEX_GENERIC_259_BUSINESS_RULE_VIOLATION"
    ONEX_GENERIC_260_OPERATION_CANCELLED = "ONEX_GENERIC_260_OPERATION_CANCELLED"

    @property
    def component(self) -> str:
        """Extract component name from error code."""
        parts = self.value.split("_")
        if len(parts) >= 2:
            return parts[1]
        return "UNKNOWN"

    @property
    def error_number(self) -> int:
        """Extract error number from error code."""
        parts = self.value.split("_")
        if len(parts) >= 3:
            try:
                return int(parts[2])
            except ValueError:
                pass
        return 0

    @property
    def description(self) -> str:
        """Extract description from error code."""
        parts = self.value.split("_")
        if len(parts) >= 4:
            return "_".join(parts[3:])
        return "UNKNOWN"

    def is_critical(self) -> bool:
        """Check if error is critical based on error number ranges."""
        error_num = self.error_number
        # Critical ranges: 001-010 (core system), 091-100 (security)
        return (1 <= error_num <= 10) or (91 <= error_num <= 100)

    def is_retryable(self) -> bool:
        """Check if error is typically retryable."""
        # Network, timeout, and resource exhaustion errors are usually retryable
        retryable_codes = {
            "ONEX_CORE_071_NETWORK_ERROR",
            "ONEX_CORE_073_TIMEOUT_ERROR",
            "ONEX_CORE_077_RATE_LIMIT_EXCEEDED",
            "ONEX_CORE_008_RESOURCE_EXHAUSTED",
            "ONEX_EXT_192_SERVICE_TIMEOUT",
            "ONEX_EXT_193_SERVICE_UNAVAILABLE",
            "ONEX_EXT_196_RATE_LIMITED",
            "ONEX_DB_111_CONNECTION_FAILED",
            "ONEX_DB_115_DEADLOCK_DETECTED",
        }
        return self.value in retryable_codes