# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Hardcoded localhost-URL validator — canonical COMPUTE node (OMN-13480, G2).

The residual G2 mechanical scanner of the validator-standardization plan
(``docs/tracking/2026-06-18-validator-standardization-remediation-plan.md`` §1A/§1B,
§5 G2) under OMN-13294: a BLOCKING gate for hardcoded ``http(s)://localhost`` /
``http(s)://127.0.0.1`` URL literals. The scanning logic was GENERATED by
``node_generation_consumer`` (omnimarket), local-model-first through the real
delegation chain, and accepted ONLY because it passed a deterministic acceptance
corpus (``node_generation_consumer.validator_corpora.corpus_hardcoded_localhost_url``)
in the hardened sandbox — the corpus verdict, not the LLM, is the acceptance
authority (OMN-13289). See ``GENERATION_PROVENANCE.md``.

Coverage rationale (why this is NOT a duplicate of ``validator_url_authority``):
url-authority's ``public-https-literal`` rule deliberately EXCLUDES localhost /
loopback (it requires a dotted TLD), and its ``url-const-assignment`` rule only
catches a loopback literal assigned to a ``*_URL`` / ``*_ENDPOINT`` constant. A
loopback URL in any OTHER context — a call arg, a dict value, a list element, a
non-URL-named variable — is uncovered. ``validate_no_env_fallbacks`` (OMN-10741)
only catches the fallback/default idiom (``os.environ.get("X", "localhost...")``,
``default="localhost..."``). This validator flags ANY ``http(s)://localhost|127.0.0.1``
literal regardless of context, closing that gap.

Architecture (§1A — validator = COMPUTE node over a swappable bus), mirroring the
private-IP / local-paths canaries:

* ``ModelLocalhostUrlScanInput`` / ``ModelLocalhostUrlScanResult`` — typed
  envelope payload + verdict (``models``).
* ``HandlerLocalhostUrlCompute`` — a pure, deterministic COMPUTE handler
  implementing ``ProtocolMessageHandler``; it reads the file *content text* from
  the envelope payload and returns findings as ``ModelHandlerOutput.result``. It
  performs NO I/O — that is what preserves COMPUTE purity.
* ``runtime_localhost_url`` — the runner: the EFFECT boundary that loads the
  staged file set (the I/O) and dispatches each file as a command envelope to the
  COMPUTE handler **over the event bus** — in-memory backend at pre-commit time,
  Kafka in CI. Same handler; only the backend (config) changes.
"""

from __future__ import annotations

from omnibase_core.validation.localhost_url.handler import (
    HandlerLocalhostUrlCompute,
    scan_source,
)
from omnibase_core.validation.localhost_url.models import (
    ModelLocalhostUrlFinding,
    ModelLocalhostUrlScanInput,
    ModelLocalhostUrlScanResult,
)

__all__ = [
    "HandlerLocalhostUrlCompute",
    "ModelLocalhostUrlFinding",
    "ModelLocalhostUrlScanInput",
    "ModelLocalhostUrlScanResult",
    "scan_source",
]
