# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Doc-content validator — canonical COMPUTE node (OMN-13569, G2).

The scanning logic was GENERATED by ``node_generation_consumer`` (omnimarket),
local-model-first through the real delegation chain, and accepted ONLY because it
passed a deterministic acceptance corpus
(``node_generation_consumer.validator_corpora.corpus_doc_content_scan``) in the
hardened sandbox — the corpus verdict, not the LLM, is the acceptance authority
(OMN-13289). See ``GENERATION_PROVENANCE.md``.

Invariant: a documentation file (``*.md`` / ``.mdx`` / ``.rst`` / ``.txt`` /
``.adoc``) must not carry local-environment traces (RFC1918 LAN IP literals,
``.201`` / ``.200`` host shorthand, personal ``/Users|/home`` paths, ``ssh
user@host`` lines, personal e-mail) or Linear ticket references (``OMN-<digits>``),
except where exempt (``localhost`` / loopback / RFC5737 doc IPs / ``example.com`` /
portable env-var forms; ``doc-content-ok`` / ``doc-content-file-ok`` suppression;
``OMN-<digits>`` under ``onex_change_control/`` or ``contracts/``).

Architecture (§1A — validator = COMPUTE node over a swappable bus), mirroring the
private-IP validator:

* ``ModelDocContentScanInput`` / ``ModelDocContentScanResult`` — typed envelope
  payload + verdict (``models``).
* ``HandlerDocContentScanCompute`` — a pure, deterministic COMPUTE handler
  implementing ``ProtocolMessageHandler``; it reads the file *content text* (and
  *path label*) from the envelope payload and returns findings as
  ``ModelHandlerOutput.result``. It performs NO I/O.
* ``runtime_doc_content_scan`` — the runner: the EFFECT boundary that loads the
  staged docs-only file set (the I/O) and dispatches each file as a command
  envelope to the COMPUTE handler **over the event bus** — in-memory backend at
  pre-commit time, Kafka in CI. Same handler; only the backend (config) changes.

NOT yet wired as a gate — that is OMN-13572 (deferred).
"""

from __future__ import annotations

from omnibase_core.validation.doc_content_scan.handler import (
    HandlerDocContentScanCompute,
    scan_source,
)
from omnibase_core.validation.doc_content_scan.models import (
    EnumDocViolationType,
    ModelDocContentFinding,
    ModelDocContentScanInput,
    ModelDocContentScanResult,
)

__all__ = [
    "EnumDocViolationType",
    "HandlerDocContentScanCompute",
    "ModelDocContentFinding",
    "ModelDocContentScanInput",
    "ModelDocContentScanResult",
    "scan_source",
]
