# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""No-faked-boundary validator — canonical COMPUTE node (OMN-13497).

Bans hand-written fakes / stubs of the platform's OWN inference / routing /
dispatch boundary from entering the codebase. The scanning logic was GENERATED by
``node_generation_consumer`` (omnimarket), local-model-first through the real
delegation chain, and accepted ONLY because it passed a deterministic acceptance
corpus (``node_generation_consumer.validator_corpora.corpus_no_faked_boundary``)
in the hardened sandbox — the corpus verdict, not the LLM, is the acceptance
authority (OMN-13289). See ``GENERATION_PROVENANCE.md``.

Architecture (validator = COMPUTE node over a swappable bus), mirroring the
private-IP / local-paths validators:

* ``ModelNoFakedBoundaryScanInput`` / ``ModelNoFakedBoundaryScanResult`` — typed
  envelope payload + verdict (``models``).
* ``HandlerNoFakedBoundaryCompute`` — a pure, deterministic COMPUTE handler
  implementing ``ProtocolMessageHandler``; it reads the file *content text* from
  the envelope payload and returns findings as ``ModelHandlerOutput.result``. It
  performs NO I/O — that is what preserves COMPUTE purity.
* ``runtime_no_faked_boundary`` — the runner: the EFFECT boundary that loads the
  staged file set (the I/O) and dispatches each file as a command envelope to the
  COMPUTE handler **over the event bus** — in-memory backend at pre-commit time,
  Kafka in CI. Same handler; only the backend (config) changes.
"""

from __future__ import annotations

from omnibase_core.validation.no_faked_boundary.handler import (
    HandlerNoFakedBoundaryCompute,
)
from omnibase_core.validation.no_faked_boundary.models import (
    ModelNoFakedBoundaryFinding,
    ModelNoFakedBoundaryScanInput,
    ModelNoFakedBoundaryScanResult,
)

__all__ = [
    "HandlerNoFakedBoundaryCompute",
    "ModelNoFakedBoundaryFinding",
    "ModelNoFakedBoundaryScanInput",
    "ModelNoFakedBoundaryScanResult",
]
