# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Unit tests for gen_hook_bits.py — generator for hook_bits.sh."""

from __future__ import annotations

import functools
import operator
import subprocess
from pathlib import Path

from omnibase_core.enums.enum_hook_bit import EnumHookBit

REPO = Path(__file__).resolve().parents[3]
SCRIPT = REPO / "scripts" / "gen_hook_bits.py"


def _run(*args: str, cwd: Path = REPO) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["uv", "run", "python", str(SCRIPT), *args],
        cwd=cwd,
        capture_output=True,
        text=True,
        check=False,
    )


def _generated_content(tmp_path: Path) -> str:
    out = tmp_path / "hook_bits.sh"
    r = _run("--write", str(out))
    assert r.returncode == 0, r.stderr
    return out.read_text()


class TestGenHookBitsHeader:
    def test_emits_generated_header(self, tmp_path: Path) -> None:
        content = _generated_content(tmp_path)
        assert "GENERATED BY omnibase_core/scripts/gen_hook_bits.py" in content
        assert "DO NOT EDIT" in content


class TestGenHookBitsEnumCoverage:
    def test_every_member_in_associative_array(self, tmp_path: Path) -> None:
        content = _generated_content(tmp_path)
        for m in EnumHookBit:
            assert f"[{m.name}]=0x{int(m):x}" in content

    def test_default_mask_equals_or_of_all_bits(self, tmp_path: Path) -> None:
        expected = functools.reduce(operator.or_, (int(m) for m in EnumHookBit))
        content = _generated_content(tmp_path)
        assert f"HOOK_BITS_DEFAULT_MASK=0x{expected:x}" in content


class TestGenHookBitsBashFunctions:
    def test_hook_bits_parse_mask_function(self, tmp_path: Path) -> None:
        content = _generated_content(tmp_path)
        assert "hook_bits_parse_mask()" in content

    def test_hook_bits_is_enabled_function(self, tmp_path: Path) -> None:
        content = _generated_content(tmp_path)
        assert "hook_bits_is_enabled()" in content
        assert "(( mask & bit ))" in content


class TestGenHookBitsCheckMode:
    def test_check_succeeds_on_round_trip(self, tmp_path: Path) -> None:
        out = tmp_path / "hook_bits.sh"
        r_write = _run("--write", str(out))
        assert r_write.returncode == 0, r_write.stderr
        r_check = _run("--check", str(out))
        assert r_check.returncode == 0, r_check.stderr

    def test_check_fails_on_drift(self, tmp_path: Path) -> None:
        stale = tmp_path / "hook_bits.sh"
        stale.write_text("# stale garbage\n")
        r = _run("--check", str(stale))
        assert r.returncode == 1
        assert "drift" in r.stderr.lower()

    def test_check_fails_on_missing_file(self, tmp_path: Path) -> None:
        missing = tmp_path / "nonexistent_hook_bits.sh"
        r = _run("--check", str(missing))
        assert r.returncode == 1
        assert "does not exist" in r.stderr.lower()


class TestGenHookBitsBashExecution:
    def test_bash_syntax_valid(self, tmp_path: Path) -> None:
        out = tmp_path / "hook_bits.sh"
        _run("--write", str(out))
        r = subprocess.run(
            ["bash", "-n", str(out)], capture_output=True, text=True, check=False
        )
        assert r.returncode == 0, r.stderr

    def test_hook_bits_is_enabled_returns_true(self, tmp_path: Path) -> None:
        out = tmp_path / "hook_bits.sh"
        _run("--write", str(out))
        r = subprocess.run(
            [
                "bash",
                "-c",
                f'source "{out}" && hook_bits_is_enabled "$HOOK_BITS_DEFAULT_MASK" "${{HOOK_BITS_BY_NAME[CI_REMINDER]}}" && echo OK',
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        assert r.returncode == 0
        assert "OK" in r.stdout

    def test_hook_bits_is_enabled_returns_false(self, tmp_path: Path) -> None:
        out = tmp_path / "hook_bits.sh"
        _run("--write", str(out))
        r = subprocess.run(
            [
                "bash",
                "-c",
                f'source "{out}" && hook_bits_is_enabled 0 "${{HOOK_BITS_BY_NAME[CI_REMINDER]}}" && echo OK || echo NOPE',
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        assert "NOPE" in r.stdout

    def test_parse_mask_hex(self, tmp_path: Path) -> None:
        out = tmp_path / "hook_bits.sh"
        _run("--write", str(out))
        r = subprocess.run(
            [
                "bash",
                "-c",
                f'source "{out}" && hook_bits_parse_mask 0xff',
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        assert r.returncode == 0
        assert "255" in r.stdout

    def test_parse_mask_binary(self, tmp_path: Path) -> None:
        out = tmp_path / "hook_bits.sh"
        _run("--write", str(out))
        r = subprocess.run(
            [
                "bash",
                "-c",
                f'source "{out}" && hook_bits_parse_mask 0b11111111',
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        assert r.returncode == 0
        assert "255" in r.stdout

    def test_parse_mask_decimal(self, tmp_path: Path) -> None:
        out = tmp_path / "hook_bits.sh"
        _run("--write", str(out))
        r = subprocess.run(
            [
                "bash",
                "-c",
                f'source "{out}" && hook_bits_parse_mask 42',
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        assert r.returncode == 0
        assert "42" in r.stdout

    def test_parse_mask_empty_returns_default(self, tmp_path: Path) -> None:
        out = tmp_path / "hook_bits.sh"
        _run("--write", str(out))
        default_mask = functools.reduce(operator.or_, (int(m) for m in EnumHookBit))
        r = subprocess.run(
            [
                "bash",
                "-c",
                f'source "{out}" 2>/dev/null && hook_bits_parse_mask ""',
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        assert r.returncode == 0
        assert str(default_mask) in r.stdout
