# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""FROZEN canonical handler-shape ratchet baseline — OMN-14355.

Generated by ``scripts/ci/canonical_handler_shape.py --update``. Do not edit by hand.

``NON_CANONICAL`` is the frozen set of nodes whose contract-declared handler is not
the canonical typed-payload shape (definition B). It is monotonically
NON-INCREASING: it may only shrink. A node leaves this set (flips canonical) ONLY
with a committed adequacy receipt under ``scripts/ci/adequacy_receipts/`` — a shape
flip alone is not proof of equivalence (the OMN-14208 trap). A NEW non-canonical
node, or growth of this set, HARD-FAILS CI + pre-commit. Retirement mechanism = the
RSD canonical rewrite regenerating these handlers, each with an adequacy receipt.
"""

NON_CANONICAL: tuple[str, ...] = ()
