# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""Import-layering GROWTH RATCHET for omnibase_core (OMN-14340, epic OMN-3210).

The intra-core import-linter oracle (`.importlinter`) freezes known back-edges as
wildcard `ignore_imports` lines. A wildcard ignore is permissive: it silently
allows *new* edges of that class to be added. This ratchet closes that gap for the
two families the operator ruled "no permanent exception" on, without doing the
deferred DTO relocation (which rides the RSD canonical rewrite):

1. **protocols -> models** (65 direct edges): frozen. A NEW protocols->models edge
   hard-fails. The set only SHRINKS; retirement = the RSD rewrite regenerating
   those modules canonically (which dissolves the protocols<->models cycle).

2. **Hub inbound** (`utils` / `mixins` / `protocols`): a NEW module importing into
   a hub hard-fails. Existing importers are grandfathered. This stops the hub
   tangle from compounding WITHOUT dissolving the hubs (dissolution also waits for
   the rewrite).

Mechanism: `grimp` (import-linter's own graph builder) enumerates the current
direct edges; a committed baseline (`scripts/ci/import_ratchet_baseline.py`,
generated) freezes the allowed sets as plain tuples; any edge/importer not in the
baseline is a violation.

Regenerate the baseline (sanctioned DOWNWARD re-freeze only — e.g. after the RSD
rewrite removes edges, or an operator-approved reduction)::

    uv run python scripts/ci/check_import_ratchet.py --update

Run the check (CI + pre-commit)::

    uv run python scripts/ci/check_import_ratchet.py
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path
from typing import TypedDict

import grimp

PACKAGE = "omnibase_core"

# Hub modules that bridge nearly every sub-package (see `.importlinter` header).
# New inbound edges into these are frozen to stop the tangle compounding.
HUBS: tuple[str, ...] = ("utils", "mixins", "protocols")

# Frozen ceiling for protocols -> models direct edges. This is the headline
# "no permanent exception" number: it may only DECREASE (retirement = RSD
# canonical rewrite). Growth past this hard-fails; lowering it is sanctioned.
FROZEN_PROTOCOLS_MODELS_MAX = 65

BASELINE_PATH = Path(__file__).with_name("import_ratchet_baseline.py")

# Header stamped into the generated baseline module (SPDX + provenance).
_BASELINE_HEADER = '''# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""FROZEN import-layering growth-ratchet baseline — OMN-14340 (epic OMN-3210).

Generated by ``scripts/ci/check_import_ratchet.py --update``. Do not edit by hand.

Each set below is monotonically NON-INCREASING: it may only shrink. Retirement
mechanism = the RSD canonical rewrite regenerating these modules (owner: RSD
rewrite epic), at which point the sets drain to empty and this file + its ratchet
are deleted.

A NEW protocols->models edge, or a NEW module importing into the utils / mixins /
protocols hubs, hard-fails CI + pre-commit. Do not add the dependency; if it is
genuinely unavoidable it needs operator sign-off, after which this baseline is
regenerated:  uv run python scripts/ci/check_import_ratchet.py --update
"""
'''


class EdgeSets(TypedDict):
    """The frozen-family edge sets, current or baseline.

    ``protocols_to_models``: sorted ``"<importer> -> <imported>"`` strings.
    ``hub_inbound``: ``{hub: sorted list of external importer modules}``.
    """

    protocols_to_models: list[str]
    hub_inbound: dict[str, list[str]]


def _under(module: str, subpackage: str) -> bool:
    """True if ``module`` is the given omnibase_core sub-package or beneath it."""
    root = f"{PACKAGE}.{subpackage}"
    return module == root or module.startswith(f"{root}.")


def compute_current_edges() -> EdgeSets:
    """Enumerate the current frozen-family edges via grimp."""
    graph = grimp.build_graph(PACKAGE)
    modules = graph.modules

    protocols_to_models: set[str] = set()
    hub_inbound: dict[str, set[str]] = {hub: set() for hub in HUBS}

    for importer in modules:
        imported_set = graph.find_modules_directly_imported_by(importer)
        importer_in_protocols = _under(importer, "protocols")
        for imported in imported_set:
            if importer_in_protocols and _under(imported, "models"):
                protocols_to_models.add(f"{importer} -> {imported}")
            for hub in HUBS:
                # Inbound edge into a hub from a module OUTSIDE that hub.
                if _under(imported, hub) and not _under(importer, hub):
                    hub_inbound[hub].add(importer)

    return EdgeSets(
        protocols_to_models=sorted(protocols_to_models),
        hub_inbound={hub: sorted(hub_inbound[hub]) for hub in HUBS},
    )


def load_baseline(path: Path = BASELINE_PATH) -> EdgeSets:
    """Load the frozen baseline sets from the generated Python module."""
    if not path.exists():
        raise FileNotFoundError(
            f"Ratchet baseline missing at {path}. Generate it with "
            f"`uv run python scripts/ci/check_import_ratchet.py --update`."
        )
    spec = importlib.util.spec_from_file_location("import_ratchet_baseline", path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise ImportError(f"Cannot load baseline module from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    pm_raw = getattr(module, "PROTOCOLS_TO_MODELS", ())
    hub_raw = getattr(module, "HUB_INBOUND", {})
    return EdgeSets(
        protocols_to_models=[str(edge) for edge in pm_raw],
        hub_inbound={hub: [str(m) for m in hub_raw.get(hub, ())] for hub in HUBS},
    )


def _render_tuple(items: list[str], indent: int) -> str:
    """Render a sorted str tuple as canonical (ruff-clean) Python source."""
    if not items:
        return "()"
    pad = " " * indent
    inner = "".join(f'{pad}    "{item}",\n' for item in items)
    return f"(\n{inner}{pad})"


def write_baseline(current: EdgeSets, path: Path = BASELINE_PATH) -> None:
    """Serialize ``current`` sets as the generated baseline Python module."""
    parts = [
        _BASELINE_HEADER,
        f"PROTOCOLS_TO_MODELS: tuple[str, ...] = "
        f"{_render_tuple(current['protocols_to_models'], 0)}",
        "",
        "HUB_INBOUND: dict[str, tuple[str, ...]] = {",
    ]
    for hub in HUBS:
        parts.append(f'    "{hub}": {_render_tuple(current["hub_inbound"][hub], 4)},')
    parts.append("}")
    path.write_text("\n".join(parts) + "\n", encoding="utf-8")


def find_violations(current: EdgeSets, baseline: EdgeSets) -> dict[str, list[str]]:
    """Return NEW edges/importers present in ``current`` but not the baseline.

    Keys: ``protocols_to_models`` and ``hub:<name>``. Empty dict == clean.
    """
    violations: dict[str, list[str]] = {}

    cur_pm = set(current["protocols_to_models"])
    base_pm = set(baseline["protocols_to_models"])
    new_pm = sorted(cur_pm - base_pm)
    if new_pm:
        violations["protocols_to_models"] = new_pm
    # Ceiling teeth: even if the baseline were tampered upward, the frozen max holds.
    if len(cur_pm) > FROZEN_PROTOCOLS_MODELS_MAX:
        violations.setdefault("protocols_to_models", [])
        violations["protocols_to_models"].append(
            f"<count {len(cur_pm)} exceeds frozen max {FROZEN_PROTOCOLS_MODELS_MAX}>"
        )

    for hub in HUBS:
        new_importers = sorted(
            set(current["hub_inbound"].get(hub, []))
            - set(baseline["hub_inbound"].get(hub, []))
        )
        if new_importers:
            violations[f"hub:{hub}"] = new_importers

    return violations


def _format_report(violations: dict[str, list[str]]) -> str:
    lines = [
        "Import-layering growth ratchet FAILED (OMN-14340, epic OMN-3210).",
        "",
        "New forbidden import edge(s) were introduced. These families are frozen",
        "non-increasing while the DTO relocation is deferred to the RSD canonical",
        "rewrite. Do NOT add the dependency; import from a properly-layered module",
        "instead. If genuinely unavoidable, get operator sign-off and regenerate the",
        "baseline: uv run python scripts/ci/check_import_ratchet.py --update",
        "",
    ]
    if "protocols_to_models" in violations:
        lines.append("  protocols -> models (frozen at 65):")
        lines += [f"    + {e}" for e in violations["protocols_to_models"]]
    for hub in HUBS:
        key = f"hub:{hub}"
        if key in violations:
            lines.append(f"  new module(s) importing into hub '{hub}':")
            lines += [f"    + {m}" for m in violations[key]]
    return "\n".join(lines)


def _counts(edges: EdgeSets) -> tuple[int, dict[str, int]]:
    return (
        len(edges["protocols_to_models"]),
        {hub: len(edges["hub_inbound"].get(hub, [])) for hub in HUBS},
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update",
        action="store_true",
        help="Regenerate the frozen baseline from the current graph (DOWNWARD "
        "re-freeze only; sanctioned for RSD-rewrite reductions / operator-approved).",
    )
    parser.add_argument(
        "--baseline",
        type=Path,
        default=BASELINE_PATH,
        help="Path to the ratchet baseline module.",
    )
    args = parser.parse_args(argv)

    current = compute_current_edges()
    pm, hub_counts = _counts(current)

    if args.update:
        write_baseline(current, args.baseline)
        print(
            f"Regenerated {args.baseline} — protocols->models={pm}, "
            f"hub_inbound={hub_counts}"
        )
        return 0

    baseline = load_baseline(args.baseline)
    violations = find_violations(current, baseline)
    if violations:
        print(_format_report(violations), file=sys.stderr)
        return 1

    print(
        "Import-layering growth ratchet OK — "
        f"protocols->models={pm} (frozen max {FROZEN_PROTOCOLS_MODELS_MAX}), "
        f"hub_inbound={hub_counts}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
