# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""Import-layering GROWTH RATCHET for omnibase_core (OMN-14340, epic OMN-3210).

The intra-core import-linter oracle (`.importlinter`) freezes known back-edges as
wildcard `ignore_imports` lines. A wildcard ignore is permissive: it silently
allows *new* edges of that class to be added. This ratchet closes that gap for the
two families the operator ruled "no permanent exception" on, without doing the
deferred DTO relocation (which rides the RSD canonical rewrite):

1. **protocols -> models** (65 direct edges): frozen, HARD-FAIL. A NEW
   protocols->models edge hard-fails. The set only SHRINKS; retirement = the RSD
   rewrite regenerating those modules canonically (dissolving the cycle).

2. **Hub inbound** (`utils` / `mixins` / `protocols`): a NEW module importing into
   a hub is tracked. Enforcement is tiered so a doomed, high-fan-in hub does not
   generate friction that gets routed around (rule #5):

   - ``mixins`` (17 importers) and ``protocols`` (63) are low-churn -> **HARD-FAIL**
     on a new importer.
   - ``utils`` (548 importers) is high-churn and scheduled for dissolution in the
     RSD rewrite anyway -> **WARN** only (net-new importers are logged and show in
     the baseline diff, but do NOT block; exit stays 0). Operator decision
     2026-07-10: a hard freeze on utils fires on most new files -> friction ->
     gets routed around -> not real enforcement.

Mechanism: `grimp` (import-linter's own graph builder) enumerates the current
direct edges; a committed baseline (`scripts/ci/import_ratchet_baseline.py`,
generated) freezes the allowed sets as plain tuples; any edge/importer not in the
baseline is a hard violation (protocols->models, mixins, protocols) or a
non-blocking warning (utils).

Regenerate the baseline (sanctioned DOWNWARD re-freeze only — e.g. after the RSD
rewrite removes edges, or an operator-approved reduction)::

    uv run python scripts/ci/check_import_ratchet.py --update

Run the check (CI + pre-commit)::

    uv run python scripts/ci/check_import_ratchet.py
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path
from typing import TypedDict

import grimp

PACKAGE = "omnibase_core"

# Hub modules that bridge nearly every sub-package (see `.importlinter` header).
# All three are frozen in the baseline; enforcement is tiered below.
HUBS: tuple[str, ...] = ("utils", "mixins", "protocols")

# Low-churn hubs whose new importers HARD-FAIL.
HARD_FAIL_HUBS: tuple[str, ...] = ("mixins", "protocols")

# High-churn, RSD-doomed hubs whose new importers only WARN (non-blocking).
WARN_HUBS: tuple[str, ...] = ("utils",)

# OMN-14291 relocates four service-wrapper framework bases from
# ``models.services`` to ``nodes`` to retire the models -> nodes back-edge. They
# are not new mixins-hub consumers; they are the same wrappers at their correct
# architectural address. Keep the alias narrow so unrelated new mixins importers
# still hard-fail.
HUB_IMPORTER_RELOCATIONS: dict[str, dict[str, str]] = {
    "mixins": {
        "omnibase_core.nodes.node_service_compute": (
            "omnibase_core.models.services.model_service_compute"
        ),
        "omnibase_core.nodes.node_service_effect": (
            "omnibase_core.models.services.model_service_effect"
        ),
        "omnibase_core.nodes.node_service_orchestrator": (
            "omnibase_core.models.services.model_service_orchestrator"
        ),
        "omnibase_core.nodes.node_service_reducer": (
            "omnibase_core.models.services.model_service_reducer"
        ),
    },
}

# Frozen ceiling for protocols -> models direct edges. This is the headline
# "no permanent exception" number: it may only DECREASE (retirement = RSD
# canonical rewrite). Growth past this hard-fails; lowering it is sanctioned.
FROZEN_PROTOCOLS_MODELS_MAX = 65

BASELINE_PATH = Path(__file__).with_name("import_ratchet_baseline.py")

# Header stamped into the generated baseline module (SPDX + provenance).
_BASELINE_HEADER = '''# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""FROZEN import-layering growth-ratchet baseline — OMN-14340 (epic OMN-3210).

Generated by ``scripts/ci/check_import_ratchet.py --update``. Do not edit by hand.

Each set below is monotonically NON-INCREASING: it may only shrink. Retirement
mechanism = the RSD canonical rewrite regenerating these modules (owner: RSD
rewrite epic), at which point the sets drain to empty and this file + its ratchet
are deleted.

A NEW protocols->models edge, or a NEW module importing into the mixins /
protocols hubs, HARD-FAILS CI + pre-commit. New importers into the utils hub only
WARN (high-churn, RSD-doomed hub — operator decision). Do not add the dependency;
if it is genuinely unavoidable it needs operator sign-off, after which this
baseline is regenerated:  uv run python scripts/ci/check_import_ratchet.py --update
"""
'''


class EdgeSets(TypedDict):
    """The frozen-family edge sets, current or baseline.

    ``protocols_to_models``: sorted ``"<importer> -> <imported>"`` strings.
    ``hub_inbound``: ``{hub: sorted list of external importer modules}``.
    """

    protocols_to_models: list[str]
    hub_inbound: dict[str, list[str]]


def _under(module: str, subpackage: str) -> bool:
    """True if ``module`` is the given omnibase_core sub-package or beneath it."""
    root = f"{PACKAGE}.{subpackage}"
    return module == root or module.startswith(f"{root}.")


def compute_current_edges() -> EdgeSets:
    """Enumerate the current frozen-family edges via grimp."""
    graph = grimp.build_graph(PACKAGE)
    modules = graph.modules

    protocols_to_models: set[str] = set()
    hub_inbound: dict[str, set[str]] = {hub: set() for hub in HUBS}

    for importer in modules:
        imported_set = graph.find_modules_directly_imported_by(importer)
        importer_in_protocols = _under(importer, "protocols")
        for imported in imported_set:
            if importer_in_protocols and _under(imported, "models"):
                protocols_to_models.add(f"{importer} -> {imported}")
            for hub in HUBS:
                # Inbound edge into a hub from a module OUTSIDE that hub.
                if _under(imported, hub) and not _under(importer, hub):
                    hub_inbound[hub].add(importer)

    return EdgeSets(
        protocols_to_models=sorted(protocols_to_models),
        hub_inbound={hub: sorted(hub_inbound[hub]) for hub in HUBS},
    )


def load_baseline(path: Path = BASELINE_PATH) -> EdgeSets:
    """Load the frozen baseline sets from the generated Python module."""
    if not path.exists():
        raise FileNotFoundError(
            f"Ratchet baseline missing at {path}. Generate it with "
            f"`uv run python scripts/ci/check_import_ratchet.py --update`."
        )
    spec = importlib.util.spec_from_file_location("import_ratchet_baseline", path)
    if spec is None or spec.loader is None:  # pragma: no cover - defensive
        raise ImportError(f"Cannot load baseline module from {path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)

    pm_raw = getattr(module, "PROTOCOLS_TO_MODELS", ())
    hub_raw = getattr(module, "HUB_INBOUND", {})
    return EdgeSets(
        protocols_to_models=[str(edge) for edge in pm_raw],
        hub_inbound={hub: [str(m) for m in hub_raw.get(hub, ())] for hub in HUBS},
    )


def _render_tuple(items: list[str], indent: int) -> str:
    """Render a sorted str tuple as canonical (ruff-clean) Python source."""
    if not items:
        return "()"
    pad = " " * indent
    inner = "".join(f'{pad}    "{item}",\n' for item in items)
    return f"(\n{inner}{pad})"


def write_baseline(current: EdgeSets, path: Path = BASELINE_PATH) -> None:
    """Serialize ``current`` sets as the generated baseline Python module."""
    parts = [
        _BASELINE_HEADER,
        f"PROTOCOLS_TO_MODELS: tuple[str, ...] = "
        f"{_render_tuple(current['protocols_to_models'], 0)}",
        "",
        "HUB_INBOUND: dict[str, tuple[str, ...]] = {",
    ]
    for hub in HUBS:
        parts.append(f'    "{hub}": {_render_tuple(current["hub_inbound"][hub], 4)},')
    parts.append("}")
    path.write_text("\n".join(parts) + "\n", encoding="utf-8")


def _new_hub_importers(current: EdgeSets, baseline: EdgeSets, hub: str) -> list[str]:
    baseline_importers = set(baseline["hub_inbound"].get(hub, []))
    relocations = HUB_IMPORTER_RELOCATIONS.get(hub, {})
    return sorted(
        importer
        for importer in current["hub_inbound"].get(hub, [])
        if importer not in baseline_importers
        and relocations.get(importer) not in baseline_importers
    )


def find_violations(current: EdgeSets, baseline: EdgeSets) -> dict[str, list[str]]:
    """Return HARD-FAIL violations present in ``current`` but not the baseline.

    Covers protocols->models and the HARD_FAIL_HUBS (mixins/protocols). New
    importers into WARN_HUBS (utils) are NOT included here — see
    :func:`find_warnings`. Keys: ``protocols_to_models`` and ``hub:<name>``.
    Empty dict == clean.
    """
    violations: dict[str, list[str]] = {}

    cur_pm = set(current["protocols_to_models"])
    base_pm = set(baseline["protocols_to_models"])
    new_pm = sorted(cur_pm - base_pm)
    if new_pm:
        violations["protocols_to_models"] = new_pm
    # Ceiling teeth: even if the baseline were tampered upward, the frozen max holds.
    if len(cur_pm) > FROZEN_PROTOCOLS_MODELS_MAX:
        violations.setdefault("protocols_to_models", [])
        violations["protocols_to_models"].append(
            f"<count {len(cur_pm)} exceeds frozen max {FROZEN_PROTOCOLS_MODELS_MAX}>"
        )

    for hub in HARD_FAIL_HUBS:
        new_importers = _new_hub_importers(current, baseline, hub)
        if new_importers:
            violations[f"hub:{hub}"] = new_importers

    return violations


def find_warnings(current: EdgeSets, baseline: EdgeSets) -> dict[str, list[str]]:
    """Return non-blocking WARN items: new importers into WARN_HUBS (utils)."""
    warnings: dict[str, list[str]] = {}
    for hub in WARN_HUBS:
        new_importers = _new_hub_importers(current, baseline, hub)
        if new_importers:
            warnings[f"hub:{hub}"] = new_importers
    return warnings


def _format_report(violations: dict[str, list[str]]) -> str:
    lines = [
        "Import-layering growth ratchet FAILED (OMN-14340, epic OMN-3210).",
        "",
        "New forbidden import edge(s) were introduced. These families are frozen",
        "non-increasing while the DTO relocation is deferred to the RSD canonical",
        "rewrite. Do NOT add the dependency; import from a properly-layered module",
        "instead. If genuinely unavoidable, get operator sign-off and regenerate the",
        "baseline: uv run python scripts/ci/check_import_ratchet.py --update",
        "",
    ]
    if "protocols_to_models" in violations:
        lines.append("  protocols -> models (frozen at 65):")
        lines += [f"    + {e}" for e in violations["protocols_to_models"]]
    for hub in HARD_FAIL_HUBS:
        key = f"hub:{hub}"
        if key in violations:
            lines.append(f"  new module(s) importing into hub '{hub}':")
            lines += [f"    + {m}" for m in violations[key]]
    return "\n".join(lines)


def _format_warnings(warnings: dict[str, list[str]]) -> str:
    lines = [
        "Import-layering growth ratchet WARNING (OMN-14340) — non-blocking.",
        "New module(s) importing into a WARN-only hub (high-churn, RSD-doomed):",
    ]
    for hub in WARN_HUBS:
        key = f"hub:{hub}"
        if key in warnings:
            lines.append(f"  hub '{hub}':")
            lines += [f"    + {m}" for m in warnings[key]]
    lines.append(
        "Prefer a properly-layered module over deepening the hub; this does not fail CI."
    )
    return "\n".join(lines)


def _counts(edges: EdgeSets) -> tuple[int, dict[str, int]]:
    return (
        len(edges["protocols_to_models"]),
        {hub: len(edges["hub_inbound"].get(hub, [])) for hub in HUBS},
    )


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--update",
        action="store_true",
        help="Regenerate the frozen baseline from the current graph (DOWNWARD "
        "re-freeze only; sanctioned for RSD-rewrite reductions / operator-approved).",
    )
    parser.add_argument(
        "--baseline",
        type=Path,
        default=BASELINE_PATH,
        help="Path to the ratchet baseline module.",
    )
    args = parser.parse_args(argv)

    current = compute_current_edges()
    pm, hub_counts = _counts(current)

    if args.update:
        write_baseline(current, args.baseline)
        print(
            f"Regenerated {args.baseline} — protocols->models={pm}, "
            f"hub_inbound={hub_counts}"
        )
        return 0

    baseline = load_baseline(args.baseline)

    warnings = find_warnings(current, baseline)
    if warnings:
        print(_format_warnings(warnings), file=sys.stderr)

    violations = find_violations(current, baseline)
    if violations:
        print(_format_report(violations), file=sys.stderr)
        return 1

    print(
        "Import-layering growth ratchet OK — "
        f"protocols->models={pm} (frozen max {FROZEN_PROTOCOLS_MODELS_MAX}, hard-fail), "
        f"hub_inbound={hub_counts} (mixins/protocols hard-fail, utils warn-only)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
