# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""FROZEN RSD provenance-stamp exemption baseline — OMN-15011.

Generated by ``scripts/ci/rsd_provenance_stamp.py --update``. Do not edit by hand.

``EXEMPT_UNSTAMPED`` is the frozen set of nodes that predate the provenance-stamp
gate and therefore carry no ``.rsd_provenance.json``. It is monotonically
NON-INCREASING: it may only shrink, and only by a node acquiring a real,
gate-verified stamp (no separate flip-receipt is required — the stamp's own
recompute IS the proof). A NEW node without a stamp, or ANY growth of this set,
HARD-FAILS CI + pre-commit. Retirement mechanism = backfilling real provenance
stamps (or documented hand-authored exceptions) onto the legacy nodes below.
"""

EXEMPT_UNSTAMPED: tuple[str, ...] = (
    "omnibase_core.nodes.node_backend_secret_discipline_compute",
    "omnibase_core.nodes.node_compliance_evidence_effect",
    "omnibase_core.nodes.node_compliance_orchestrator",
    "omnibase_core.nodes.node_compliance_report_reducer",
    "omnibase_core.nodes.node_compliance_scan_compute",
    "omnibase_core.nodes.node_contract_resolve_compute",
    "omnibase_core.nodes.node_contract_verify_replay_compute",
    "omnibase_core.nodes.node_no_direct_kafka_producer_check_compute",
    "omnibase_core.nodes.node_no_env_fallbacks_check_compute",
    "omnibase_core.nodes.node_no_hardcoded_ip_check_compute",
    "omnibase_core.nodes.node_no_io_outside_effects_check_compute",
    "omnibase_core.nodes.node_no_raw_sqlite3_check_compute",
    "omnibase_core.nodes.node_no_utcnow_check_compute",
    "omnibase_core.nodes.node_routing_authority_check_compute",
    "omnibase_core.nodes.node_source_file_gather_effect",
    "omnibase_core.nodes.node_test_selector_compute",
)
