# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""FROZEN RSD provenance-stamp exemption baseline — OMN-15011.

Generated by ``scripts/ci/rsd_provenance_stamp.py --update``. Do not edit by hand.

``EXEMPT_UNSTAMPED`` is the frozen set of nodes that predate the provenance-stamp
gate and therefore carry no ``.rsd_provenance.json``. It is monotonically
NON-INCREASING: it may only shrink, and only by a node acquiring a real,
gate-verified stamp (no separate flip-receipt is required — the stamp's own
recompute IS the proof). A NEW node without a stamp, or ANY growth of this set,
HARD-FAILS CI + pre-commit. Retirement mechanism = backfilling real provenance
stamps (or documented hand-authored exceptions) onto the legacy nodes below.
"""

EXEMPT_UNSTAMPED: tuple[str, ...] = ()
