# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT

"""Permanent parity against diagnostics generated by the original script."""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from omnibase_core.models.nodes.no_untyped_metadata_check.model_no_untyped_metadata_check_input import (
    ModelNoUntypedMetadataCheckInput,
)
from omnibase_core.models.nodes.no_utcnow_check.model_source_file import ModelSourceFile
from omnibase_core.models.validation.model_validation_report import (
    ModelValidationReport,
)
from omnibase_core.nodes.node_no_untyped_metadata_check_compute.handler import (
    NodeNoUntypedMetadataCheckCompute,
)
from omnibase_core.nodes.node_no_untyped_metadata_check_compute.runtime_no_untyped_metadata_check import (
    _gather_from_root,
    main,
)

from .parity_support import CORPUS, REPO_ROOT, materialize_corpus, report_rows

pytestmark = pytest.mark.unit


def test_parity_golden_corpus(tmp_path: Path) -> None:
    paths = materialize_corpus(tmp_path)
    golden = json.loads((CORPUS / "golden.json").read_text())
    for path in paths:
        expected = golden[path.name]
        report = NodeNoUntypedMetadataCheckCompute().handle(
            ModelNoUntypedMetadataCheckInput(
                files=[ModelSourceFile(path=str(path), source=path.read_text())]
            )
        )
        assert report_rows(report, tmp_path) == expected["findings"]
        report_path = tmp_path / "report.json"
        assert (
            main([str(path), "--report-json", str(report_path)])
            == expected["exit_code"]
        )
        runtime_report = ModelValidationReport.model_validate_json(
            report_path.read_text()
        )
        assert report_rows(runtime_report, tmp_path) == expected["findings"]


def test_parity_full_repo_tree_passes(tmp_path: Path) -> None:
    root = REPO_ROOT / "src"
    files, errors = _gather_from_root(str(root))
    assert len(files) > 0
    assert errors == []
    report_path = tmp_path / "repo.json"
    assert main(["--root", str(root), "--report-json", str(report_path)]) == 0
    report = ModelValidationReport.model_validate_json(report_path.read_text())
    assert report.overall_status == "PASS"
    assert report.findings == ()
