# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Hardcoded private-IP validator — canonical COMPUTE node (OMN-13294, G2).

This package is the first G2 mass-produced mechanical scanner of the
validator-standardization plan
(``docs/tracking/2026-06-18-validator-standardization-remediation-plan.md`` §1A/§1B,
§5 G2). The scanning logic was GENERATED by ``node_generation_consumer``
(omnimarket), local-model-first through the real delegation chain, and accepted
ONLY because it passed a deterministic acceptance corpus
(``node_generation_consumer.validator_corpora.corpus_hardcoded_ip``) in the
hardened sandbox — the corpus verdict, not the LLM, is the acceptance authority
(OMN-13289). See ``GENERATION_PROVENANCE.md``.

Architecture (§1A — validator = COMPUTE node over a swappable bus), mirroring the
G1 local-paths canary:

* ``ModelPrivateIpScanInput`` / ``ModelPrivateIpScanResult`` — typed envelope
  payload + verdict (``models``).
* ``HandlerPrivateIpCompute`` — a pure, deterministic COMPUTE handler
  implementing ``ProtocolMessageHandler``; it reads the file *content text* from
  the envelope payload and returns findings as ``ModelHandlerOutput.result``. It
  performs NO I/O — that is what preserves COMPUTE purity.
* ``runtime_private_ip`` — the runner: the EFFECT boundary that loads the staged
  file set (the I/O) and dispatches each file as a command envelope to the
  COMPUTE handler **over the event bus** — in-memory backend at pre-commit time,
  Kafka in CI. Same handler; only the backend (config) changes.
"""

from __future__ import annotations

from omnibase_core.validation.private_ip.handler import HandlerPrivateIpCompute
from omnibase_core.validation.private_ip.models import (
    ModelPrivateIpFinding,
    ModelPrivateIpScanInput,
    ModelPrivateIpScanResult,
)

__all__ = [
    "HandlerPrivateIpCompute",
    "ModelPrivateIpFinding",
    "ModelPrivateIpScanInput",
    "ModelPrivateIpScanResult",
]
