# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Generate hook_bits.sh from EnumHookBit enum.

Usage:
    uv run python scripts/gen_hook_bits.py --write <path>
    uv run python scripts/gen_hook_bits.py --check <path>
"""

from __future__ import annotations

import argparse
import functools
import operator
import sys
from pathlib import Path

from omnibase_core.enums.enum_hook_bit import EnumHookBit

_HEADER = """\
#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
# GENERATED BY omnibase_core/scripts/gen_hook_bits.py — DO NOT EDIT
# Regenerate via: uv run python scripts/gen_hook_bits.py --write <this-file>
"""


def _assert_declaration_order() -> None:
    for expected_shift, m in enumerate(EnumHookBit):
        actual = int(m)
        if actual != (1 << expected_shift):
            raise RuntimeError(
                f"{m.name} has value {actual} but expected 1 << {expected_shift} "
                f"(gap or reordering detected in EnumHookBit)"
            )


def _compute_default_mask() -> int:
    return functools.reduce(operator.or_, (int(m) for m in EnumHookBit))


def render() -> str:
    lines: list[str] = [_HEADER.rstrip()]
    lines.append("")

    default_mask = _compute_default_mask()
    lines.append(f"HOOK_BITS_DEFAULT_MASK=0x{default_mask:x}")
    lines.append("")

    lines.append(
        """\
# hook_bits_bit_for_name NAME
#   Prints the bit assigned to NAME. Bash 3.2 has no associative arrays, and
#   Claude hook launchers use the system bash on macOS, so keep this table as a
#   portable case statement instead of `declare -A`.
hook_bits_bit_for_name() {
    case "${1:-}" in"""
    )
    for m in EnumHookBit:
        lines.append(f"        {m.name}) echo 0x{int(m):x} ;;")
    lines.extend(
        [
            "        *) return 1 ;;",
            "    esac",
            "}",
        ]
    )
    lines.append("")

    lines.append(
        """\
# hook_bits_parse_mask RAW
#   Parse a mask string (0x hex, 0b binary, or decimal) into a decimal integer.
#   Returns the parsed value on stdout. On failure, prints HOOK_BITS_DEFAULT_MASK.
hook_bits_parse_mask() {
    local raw="${1:-}"
    if [[ -z "$raw" ]]; then
        echo "$(( HOOK_BITS_DEFAULT_MASK ))"
        return 0
    fi
    case "$raw" in
        0x*|0X*)
            echo "$((raw))"
            ;;
        0b*)
            echo "$(( 2#${raw#0b} ))"
            ;;
        0B*)
            echo "$(( 2#${raw#0B} ))"
            ;;
        *)
            if [[ "$raw" =~ ^[0-9]+$ ]]; then
                echo "$raw"
            else
                echo "$(( HOOK_BITS_DEFAULT_MASK ))"
            fi
            ;;
    esac
}
"""
    )

    lines.append(
        """\
# hook_bits_is_enabled MASK BIT
#   Exit 0 if BIT is set in MASK, exit 1 otherwise.
#   MASK and BIT may be in any format accepted by $(( ... )).
hook_bits_is_enabled() {
    local mask="$1"
    local bit="$2"
    (( mask & bit ))
}
"""
    )

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    _assert_declaration_order()

    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--write",
        type=Path,
        metavar="PATH",
        help="Write generated bash to PATH",
    )
    p.add_argument(
        "--check",
        type=Path,
        metavar="PATH",
        help="Check PATH against fresh generation; exit 1 on drift",
    )
    args = p.parse_args(argv)

    if args.write and args.check:
        p.error("Specify exactly one of --write or --check")
        return 1

    if not args.write and not args.check:
        p.error("Specify exactly one of --write or --check")
        return 1

    rendered = render()

    if args.check:
        target = args.check
        if not target.exists():
            sys.stderr.write(
                f"hook_bits.sh drift: {target} does not exist. "
                f"Generate with: uv run python scripts/gen_hook_bits.py --write {target}\n"
            )
            return 1
        existing = target.read_text()
        if existing != rendered:
            sys.stderr.write(
                f"hook_bits.sh drift detected: {target} is stale.\n"
                f"Regenerate with: uv run python scripts/gen_hook_bits.py --write {target}\n"
            )
            return 1
        return 0

    target = args.write
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
