# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Generate hook_bits.sh from EnumHookBit enum and hook activation contract.

Usage:
    uv run python scripts/gen_hook_bits.py --contract <path> --write <path>
    uv run python scripts/gen_hook_bits.py --contract <path> --check <path>
"""

from __future__ import annotations

import argparse
import functools
import operator
import sys
from pathlib import Path

from ruamel.yaml import YAML

from omnibase_core.enums.enum_hook_bit import EnumHookBit
from omnibase_core.models.contracts.subcontracts.model_package_hook_activations import (
    ModelPackageHookActivations,
)

_HEADER = """\
#!/usr/bin/env bash
# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
# GENERATED BY omnibase_core/scripts/gen_hook_bits.py — DO NOT EDIT
# Regenerate via: uv run python scripts/gen_hook_bits.py --contract <hook_activations.yaml> --write <this-file>
"""


def _assert_declaration_order() -> None:
    for expected_shift, m in enumerate(EnumHookBit):
        actual = int(m)
        if actual != (1 << expected_shift):
            raise RuntimeError(
                f"{m.name} has value {actual} but expected 1 << {expected_shift} "
                f"(gap or reordering detected in EnumHookBit)"
            )


def _infer_contract_path(target: Path | None) -> Path | None:
    if target is None:
        return None
    for parent in [target.parent, *target.parents]:
        candidate = parent / "src/omniclaude/contracts/hook_activations.yaml"
        if candidate.exists():
            return candidate
    return None


def _load_disabled_by_default(contract_path: Path) -> frozenset[str]:
    if not contract_path.exists():
        raise FileNotFoundError(f"hook activation contract not found: {contract_path}")

    yaml = YAML(typ="safe")
    raw = yaml.load(contract_path.read_text())
    contract = ModelPackageHookActivations.model_validate(raw)
    contract_names = [
        activation.hook_bit.name for activation in contract.hook_activations
    ]
    enum_names = [member.name for member in EnumHookBit]

    missing = sorted(set(enum_names) - set(contract_names))
    extra = sorted(set(contract_names) - set(enum_names))
    duplicates = sorted(
        name for name in set(contract_names) if contract_names.count(name) > 1
    )
    if missing or extra or duplicates:
        details: list[str] = []
        if missing:
            details.append(f"missing={missing}")
        if extra:
            details.append(f"extra={extra}")
        if duplicates:
            details.append(f"duplicates={duplicates}")
        raise ValueError(
            "hook activation contract does not exactly match EnumHookBit: "
            + ", ".join(details)
        )

    return frozenset(
        activation.hook_bit.name
        for activation in contract.hook_activations
        if not activation.enabled_by_default
    )


def _resolve_contract_path(contract_path: Path | None, target: Path | None) -> Path:
    resolved = contract_path or _infer_contract_path(target)
    if resolved is None:
        raise ValueError(
            "hook activation contract is required; pass --contract "
            "src/omniclaude/contracts/hook_activations.yaml"
        )
    return resolved


def _compute_default_mask(disabled_by_default: frozenset[str]) -> int:
    return functools.reduce(
        operator.or_,
        (int(m) for m in EnumHookBit if m.name not in disabled_by_default),
        0,
    )


def render(contract_path: Path) -> str:
    lines: list[str] = [_HEADER.rstrip()]
    lines.append("")

    disabled_by_default = _load_disabled_by_default(contract_path)
    default_mask = _compute_default_mask(disabled_by_default)
    lines.append(f"HOOK_BITS_DEFAULT_MASK=0x{default_mask:x}")
    if disabled_by_default:
        lines.append(
            'HOOK_BITS_DISABLED_BY_DEFAULT="'
            + " ".join(sorted(disabled_by_default))
            + '"'
        )
    else:
        lines.append("HOOK_BITS_DISABLED_BY_DEFAULT=")
    lines.append("")

    lines.append(
        """\
# hook_bits_bit_for_name NAME
#   Prints the bit assigned to NAME. Bash 3.2 has no associative arrays, and
#   Claude hook launchers use the system bash on macOS, so keep this table as a
#   portable case statement instead of `declare -A`.
hook_bits_bit_for_name() {
    case "${1:-}" in"""
    )
    for m in EnumHookBit:
        lines.append(f"        {m.name}) echo 0x{int(m):x} ;;")
    lines.extend(
        [
            "        *) return 1 ;;",
            "    esac",
            "}",
        ]
    )
    lines.append("")

    lines.append(
        """\
# hook_bits_parse_mask RAW
#   Parse a mask string (0x hex, 0b binary, or decimal) into a decimal integer.
#   Returns the parsed value on stdout. On failure, prints HOOK_BITS_DEFAULT_MASK.
hook_bits_parse_mask() {
    local raw="${1:-}"
    if [[ -z "$raw" ]]; then
        echo "$(( HOOK_BITS_DEFAULT_MASK ))"
        return 0
    fi
    case "$raw" in
        0x*|0X*)
            echo "$((raw))"
            ;;
        0b*)
            echo "$(( 2#${raw#0b} ))"
            ;;
        0B*)
            echo "$(( 2#${raw#0B} ))"
            ;;
        *)
            if [[ "$raw" =~ ^[0-9]+$ ]]; then
                echo "$raw"
            else
                echo "$(( HOOK_BITS_DEFAULT_MASK ))"
            fi
            ;;
    esac
}
"""
    )

    lines.append(
        """\
# hook_bits_is_enabled MASK BIT
#   Exit 0 if BIT is set in MASK, exit 1 otherwise.
#   MASK and BIT may be in any format accepted by $(( ... )).
hook_bits_is_enabled() {
    local mask="$1"
    local bit="$2"
    (( mask & bit ))
}
"""
    )

    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    _assert_declaration_order()

    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument(
        "--contract",
        type=Path,
        metavar="PATH",
        help=(
            "Read enabled_by_default values from hook_activations.yaml. If omitted, "
            "the path is inferred from an omniclaude hook_bits.sh target."
        ),
    )
    p.add_argument(
        "--write",
        type=Path,
        metavar="PATH",
        help="Write generated bash to PATH",
    )
    p.add_argument(
        "--check",
        type=Path,
        metavar="PATH",
        help="Check PATH against fresh generation; exit 1 on drift",
    )
    args = p.parse_args(argv)

    if args.write and args.check:
        p.error("Specify exactly one of --write or --check")
        return 1

    if not args.write and not args.check:
        p.error("Specify exactly one of --write or --check")
        return 1

    target = args.write or args.check
    try:
        contract_path = _resolve_contract_path(args.contract, target)
        rendered = render(contract_path)
    except (FileNotFoundError, ValueError) as exc:
        sys.stderr.write(f"{exc}\n")
        return 1

    if args.check:
        target = args.check
        if not target.exists():
            sys.stderr.write(
                f"hook_bits.sh drift: {target} does not exist. "
                f"Generate with: uv run python scripts/gen_hook_bits.py --write {target}\n"
            )
            return 1
        existing = target.read_text()
        if existing != rendered:
            sys.stderr.write(
                f"hook_bits.sh drift detected: {target} is stale.\n"
                f"Regenerate with: uv run python scripts/gen_hook_bits.py --write {target}\n"
            )
            return 1
        return 0

    target = args.write
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
