# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Hardcoded-absolute-path validator — canonical COMPUTE node (OMN-13293, G1).

This package is the G1 canary of the validator-standardization plan
(``docs/tracking/2026-06-18-validator-standardization-remediation-plan.md`` §1A/§1B).
The scanning logic was GENERATED by ``node_generation_consumer`` (omnimarket),
local-model-first through the real delegation chain, and accepted ONLY because it
reproduces the hand-authored ground truth
(``omnibase_core.validation.validator_local_paths``) across a deterministic
fixture corpus whose verdicts are derived from that ground truth.

Architecture (§1A — validator = COMPUTE node over a swappable bus):

* ``ModelLocalPathScanInput`` / ``ModelLocalPathScanResult`` — typed envelope
  payload + verdict (``models``).
* ``HandlerLocalPathsCompute`` — a pure, deterministic COMPUTE handler
  implementing ``ProtocolMessageHandler``; it reads the file *content text* from
  the envelope payload and returns findings as ``ModelHandlerOutput.result``.
  It performs NO I/O (no filesystem, no ``os``/``pathlib`` reads) — that is what
  preserves COMPUTE purity and makes the verdict deterministically testable.
* ``runtime_local_paths`` — the runner: the EFFECT boundary that loads the
  staged file set (the I/O) and dispatches each file as a command envelope to the
  COMPUTE handler **over the event bus** — in-memory backend at pre-commit time,
  Kafka in CI. Same handler; only the backend (config) changes.
"""

from __future__ import annotations

from omnibase_core.validation.local_paths.handler import HandlerLocalPathsCompute
from omnibase_core.validation.local_paths.models import (
    ModelLocalPathFinding,
    ModelLocalPathScanInput,
    ModelLocalPathScanResult,
)

__all__ = [
    "HandlerLocalPathsCompute",
    "ModelLocalPathFinding",
    "ModelLocalPathScanInput",
    "ModelLocalPathScanResult",
]
