# SPDX-FileCopyrightText: 2025 OmniNode.ai Inc.
# SPDX-License-Identifier: MIT
"""Sibling-pin-hygiene validator — canonical COMPUTE node (OMN-13509).

Blocks any sibling dependency pin (``omnibase-core`` / ``omnibase-spi`` /
``omnibase-compat`` git rev or ``branch=`` in ``pyproject.toml`` / ``uv.lock``)
whose pinned commit is NOT an ancestor of that sibling's ``dev`` HEAD — the real
recurrence fix for the #2071 / OMN-13507 diverged-pin saga. The scanning logic
(sibling detection, the four git-pin syntaxes, the ancestry-verdict reading) was
GENERATED by ``node_generation_consumer`` (omnimarket), local-model-first through
the real delegation chain, and accepted ONLY because it passed a deterministic
acceptance corpus
(``node_generation_consumer.validator_corpora.corpus_pin_hygiene``) in the
hardened sandbox — the corpus verdict, not the LLM, is the acceptance authority
(OMN-13289). See ``GENERATION_PROVENANCE.md``.

Architecture (validator = COMPUTE node over a swappable bus), mirroring the
private-IP / no-faked-boundary validators, with ONE deliberate difference: the
gate verdict depends on GIT ANCESTRY (I/O). To keep the COMPUTE handler pure, the
runner — the EFFECT boundary — resolves that git I/O and annotates each pin with
its ancestry before dispatch:

* ``ModelPinHygieneScanInput`` / ``ModelPinHygieneScanResult`` — typed envelope
  payload + verdict (``models``).
* ``HandlerPinHygieneCompute`` — a pure, deterministic COMPUTE handler
  implementing ``ProtocolMessageHandler``; it reads the annotated pin *content
  text* from the envelope payload and returns findings as
  ``ModelHandlerOutput.result``. It performs NO I/O — no filesystem, no git —
  that is what preserves COMPUTE purity.
* ``runtime_pin_hygiene`` — the runner: the EFFECT boundary that loads the
  ``pyproject.toml`` / ``uv.lock`` files (file I/O), resolves each sibling pin's
  ancestry against its canonical clone (``git merge-base --is-ancestor``, the git
  I/O), annotates the text, and dispatches each file as a command envelope to the
  COMPUTE handler **over the event bus** — in-memory backend at pre-commit time,
  Kafka in CI. Same handler; only the backend (config) changes.
"""

from __future__ import annotations

from omnibase_core.validation.pin_hygiene.handler import (
    HandlerPinHygieneCompute,
    scan_source,
)
from omnibase_core.validation.pin_hygiene.models import (
    ModelPinHygieneFinding,
    ModelPinHygieneScanInput,
    ModelPinHygieneScanResult,
)

__all__ = [
    "HandlerPinHygieneCompute",
    "ModelPinHygieneFinding",
    "ModelPinHygieneScanInput",
    "ModelPinHygieneScanResult",
    "scan_source",
]
