# ONEX Mixin: Event Handling
# Provides standardized event bus integration patterns for all node types

mixin_name: "mixin_event_handling"
mixin_version: {major: 1, minor: 0, patch: 0}
description: "Event bus integration and message handling patterns for ONEX nodes"
applicable_node_types: ["COMPUTE", "EFFECT", "REDUCER", "ORCHESTRATOR"]

# === EVENT HANDLING ACTIONS ===
actions:
  - name: "publish_event"
    description: "Publish an event to the event bus"
    inputs: ["event_type", "event_data", "routing_key"]
    outputs: ["publish_result", "event_id"]
    required: true
    timeout_ms: 3000

  - name: "subscribe_to_events"
    description: "Subscribe to specific event types"
    inputs: ["event_types", "subscription_config"]
    outputs: ["subscription_id", "subscription_status"]
    required: false
    timeout_ms: 2000

  - name: "unsubscribe_from_events"
    description: "Unsubscribe from event types"
    inputs: ["subscription_id"]
    outputs: ["unsubscription_status"]
    required: false
    timeout_ms: 1000

  - name: "handle_event"
    description: "Process incoming events from subscriptions"
    inputs: ["event_envelope"]
    outputs: ["processing_result", "response_events"]
    required: true
    timeout_ms: 5000

  - name: "get_event_history"
    description: "Retrieve event processing history"
    inputs: ["time_range", "event_type_filter"]
    outputs: ["event_history", "processing_stats"]
    required: false
    timeout_ms: 2000

# === EVENT CONFIGURATION ===
event_config:
  default_routing_strategy: "topic"
  event_serialization: "json"
  compression_enabled: false
  encryption_enabled: false
  dead_letter_enabled: true
  retry_policy:
    max_retries: 3
    retry_delay_ms: 1000
    exponential_backoff: true
  batch_processing:
    enabled: true
    batch_size: 10
    max_wait_ms: 5000

# === OUTPUT MODELS ===
output_models:
  event_envelope:
    event_id: "string"
    event_type: "string"
    timestamp: "datetime"
    source_node: "string"
    routing_key: "string"
    headers:
      type: "object"
      additionalProperties: "string"
    payload: "object"
    
  publish_result:
    success: "boolean"
    event_id: "string"
    delivery_status: "enum[DELIVERED,PENDING,FAILED]"
    error_message: "string"
    
  subscription_status:
    subscription_id: "string"
    active: "boolean"
    event_types:
      type: "array"
      items: "string"
    message_count: "integer"
    last_message: "datetime"
    
  processing_result:
    success: "boolean"
    processing_time_ms: "integer"
    response_events:
      type: "array"
      items:
        event_type: "string"
        event_data: "object"
    error_details: "object"

# === EVENT TYPES BY NODE TYPE ===
node_specific_events:
  COMPUTE:
    publishes: ["computation_started", "computation_completed", "computation_failed"]
    subscribes: ["computation_request", "resource_update"]
    
  EFFECT:
    publishes: ["effect_executed", "external_call_completed", "side_effect_occurred"]
    subscribes: ["effect_request", "external_event"]
    
  REDUCER:
    publishes: ["state_updated", "aggregation_completed", "state_snapshot"]
    subscribes: ["state_change_request", "aggregation_trigger"]
    
  ORCHESTRATOR:
    publishes: ["workflow_started", "workflow_completed", "coordination_event"]
    subscribes: ["task_completed", "node_status_changed", "workflow_trigger"]

# === DEPENDENCIES PROVIDED ===
dependencies:
  - name: "event_publishing"
    type: "capability"
    description: "Provides event publishing capabilities"
    
  - name: "event_subscription"
    type: "capability" 
    description: "Provides event subscription and handling capabilities"

# === DEPENDENCIES REQUIRED ===
requires_dependencies:
  - name: "protocol_event_bus"
    type: "protocol"
    description: "Event bus protocol for message transport"

# === METRICS ===
metrics:
  - name: "events_published"
    type: "counter"
    description: "Total number of events published"
    labels: ["event_type", "routing_key"]
    
  - name: "events_received"
    type: "counter"
    description: "Total number of events received"
    labels: ["event_type", "subscription_id"]
    
  - name: "event_processing_time"
    type: "histogram"
    description: "Time taken to process events"
    labels: ["event_type"]
    
  - name: "active_subscriptions"
    type: "gauge"
    description: "Number of active event subscriptions"
    
  - name: "event_processing_errors"
    type: "counter"
    description: "Number of event processing errors"
    labels: ["event_type", "error_type"]